# Generated by Django 4.1.1 on 2022-12-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_person_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='color_name',
        ),
    ]
